name: firebase_remote_config
description: Flutter plugin for Firebase Remote Config. Update your application look and feel and behaviour without
  re-releasing.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_remote_config
version: 0.4.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.3
  firebase_core_platform_interface: ^2.0.0
  firebase_remote_config_platform_interface:
    path: ../firebase_remote_config_platform_interface
dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  plugin_platform_interface: ^1.0.2
  mockito: ^4.1.1

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.firebaseremoteconfig
        pluginClass: FirebaseRemoteConfigPlugin
      ios:
         pluginClass: FirebaseRemoteConfigPlugin
      macos:
         pluginClass: FirebaseRemoteConfigPlugin

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
